"""
Django settings for auth_system project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR=os.path.join(BASE_DIR,"templates")
STATIC_DIR=os.path.join(BASE_DIR,"static")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-55qmys+yvw5u88xilu^7vd3)k-%mb85yh!m0!d!n^&!t=a&tg3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

STRIPE_TEST_PUBLIC_KEY ='pk_test_51QMqsaEeTeKgicdtLPjUOcShME6OtHSLakMOjK3wH56TUPZDfu8U7adM8by4Cmgy30NysUwBQPgcghbXlbBSpJnj00tQz2Jp0S'  # Replace with your Stripe public key
STRIPE_SECRET_KEY = 'sk_test_51QMqsaEeTeKgicdttMboVjy6RlEpcBrcwP8EQDJj5cU0cPN2npdI7GPgZFX9Zh4b8MIf3IHeHQof1lw2wewBhZop00iSsgrOpf'  # Replace with your Stripe secret key


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    "C:/Fruits_and_veges_Ecomen/Fruits_and_veges_Ecom/Ecom/static/",
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kbmagoda2024@gmail.com'
EMAIL_HOST_PASSWORD = 'flyvrujeneixhaxg' 
ALLOWED_HOSTS = []

STRIPE_SECRET_KEY = "sk_test_51QMqsaEeTeKgicdttMboVjy6RlEpcBrcwP8EQDJj5cU0cPN2npdI7GPgZFX9Zh4b8MIf3IHeHQof1lw2wewBhZop00iSsgrOpf"
STRIPE_PUBLISHABLE_KEY = "pk_test_51QMqsaEeTeKgicdtLPjUOcShME6OtHSLakMOjK3wH56TUPZDfu8U7adM8by4Cmgy30NysUwBQPgcghbXlbBSpJnj00tQz2Jp0S"
# Application definition

INSTALLED_APPS = [
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "captcha"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auth_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'auth_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    STATIC_DIR,
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
