# Generated by Django 5.1.2 on 2024-11-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('bus_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('bus_loc', models.CharField(max_length=250)),
                ('bus_email', models.CharField(max_length=250)),
                ('bus_phone', models.CharField(max_length=250)),
                ('bus_services', models.CharField(max_length=250)),
                ('add_info', models.CharField(max_length=300)),
            ],
        ),
    ]
