# Generated by Django 5.1.2 on 2024-11-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentBox', '0002_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='add_info',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='bus_loc',
            field=models.TextField(max_length=250),
        ),
    ]
